// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: query.sql

package postgres

import (
	"context"
)

const addUser = `-- name: AddUser :one
INSERT INTO users (
  id, email, name
) VALUES (
  $1, $2, $3
)
RETURNING id, email, name
`

type AddUserParams struct {
	ID    string
	Email string
	Name  string
}

func (q *Queries) AddUser(ctx context.Context, arg AddUserParams) (User, error) {
	row := q.db.QueryRow(ctx, addUser, arg.ID, arg.Email, arg.Name)
	var i User
	err := row.Scan(&i.ID, &i.Email, &i.Name)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name FROM users WHERE email=$1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(&i.ID, &i.Email, &i.Name)
	return i, err
}
